_target_: pytorch_lightning.Trainer
devices: 1
max_epochs: 300
fast_dev_run: false
deterministic: true
num_sanity_val_steps: 0
enable_progress_bar: true
enable_checkpointing: true
log_every_n_steps: 15